### ISSUE TITLE
Update a bunch of profiles

### ISSUE THREAD

**Issue by Seanny123** [ctn-waterloo/website#38]
Proposed removals:
- Oliver
- Peter Suma
- Eric Crawford

Proposed additions:
- Sean Aubin as a grad student
- Su as a???
- Mariah
- New Peter
- Get Youssef a picture by copying his Github picture

**Comment by celiasmith** [comment]
Fine in general (removal means moving to alumni, i presume), except suma 
is still technically in the lab (on a break).  Also, it's Mariah :)

best, c.

Sean Aubin wrote:
