### ISSUE TITLE
Update code to Python 3?

### ISSUE THREAD

**Issue by jgosmann** [ctn-waterloo/website#46]
It is not possible at the moment to build the website with Python 3.

**Comment by jgosmann** [comment]
This would be really nice!

**Comment by hunse** [comment]
Is there any reason we can't have it work with both?

**Comment by Seanny123** [comment]
We could make it work with both. It's just easier to only work with one.

**Comment by tbekolay** [comment]
Y'all can switch over to Python 3 or scrap the Python stuff altogether and use Jekyll, it's all good with me. I don't consider myself the owner of this code anymore, so if anyone wants to take ownership be my guest!
