### ISSUE TITLE
Allow arbitrarily tagging of publications

### ISSUE THREAD

**Issue by Seanny123** [ctn-waterloo/website#50]
Is there some way to give a list of argument to a field in Bibtex allowing for tagging of publications? For example, if someone wanted to see all publications using FPGAs or Spinnaker?

I'm starting to think this isn't actually possible with Bibtex and if anything, a seperate JSON file with the same name should contain the tags. Unfortunately, this would require updating how searching of documents is performed...

**Update:**
This is already implemented (see [this entry for an example](https://github.com/ctn-waterloo/website/blob/master/ctn_waterloo/content/publications/berzish2016.bib)), despite the fact it's [not explicitly supported by Bibtex](http://tex.stackexchange.com/questions/239042/where-can-we-find-a-list-of-all-available-bibtex-entries-and-the-available-field). So tag your stuff everyone!

**Comment by jgosmann** [comment]
`keywords` is supported by Biblatex which IMO should be used whenever possible (better Unicode support, better citation commands, more features). Unfortunately, many Journal templates still require the old bibtex. Anyways, this is somewhat irrelevant to the website which is using neither bibtex nor Biblatex, but a Python implementation to parse the bibtex files.

**Comment by Seanny123** [comment]
I was not aware there was an alternative to Bibtex. <3
