### ISSUE TITLE
Bibtex failures hard to debug

### ISSUE THREAD

**Issue by jgosmann** [ctn-waterloo/website#51]
I added a publication (`kajic2017.bib`) and the website builds fine, but it does not appear. I'm also not getting any errors, so I have no idea what's wrong.

**Comment by jgosmann** [comment]
It actually works locally on my computer, but not the live version. 😖

**Comment by jgosmann** [comment]
I suppose I found the problem. The build is marked as successful, but it actually fails with this:
```
### Uploading to cnrglab@compneuro.uwaterloo.ca:/home/cnrglab/public_html/
ssh: connect to host compneuro.uwaterloo.ca port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]
```
@tbekolay @xchoo Any idea what's the cause?

**Comment by tbekolay** [comment]
Hm... I think this is a result of UWaterloo (or WatArts) locking down SSH access only to IPs within the university. E.g., I can't SSH into compneuro from there, but if I SSH onto a machine on campus I can. The TravisCI script needs SSH access because the files are hosted on a WatArts server, but built as part of the TravisCI build. We use `rsync` to send the built files over to the WatArts server efficiently.

**Comment by jgosmann** [comment]
Bottom line: We can't deploy our website right now? How do we fix it? Is there a way to setup the required VPN connection in Travis-CI?

**Comment by tbekolay** [comment]
You can manually deploy for now... basically execute the TravisCI script from an on-campus computer. Aside from that, I'm not a student anymore so I can't talk to WatArts about a good solution.

**Comment by jgosmann** [comment]
Don't I need some sort of key for the SSH connection?

**Comment by tbekolay** [comment]
The username/password is in the CRNG Google Drive ("How To's" > "compneuro website")

**Comment by jgosmann** [comment]
Awesome, thank you!

**Comment by psipeter** [comment]
Could someone please update the CNRG Google Drive "compneuro website" document with a step-by-step description of how to manually deploy the website? Either via SSH or from an on-campus computer.

**Comment by tbekolay** [comment]
The steps are in https://github.com/ctn-waterloo/website/blob/master/.travis.yml ; ignore all the stuff about SSH keys and authenticity as you can login with the username / password (you can't do that in .travis.yml because it's publicly viewable).

**Comment by jgosmann** [comment]
Auto-deploy of the website should work again. Might be take longer before because I had to add to enable `sudo` on Travis which is regarded legacy infrastructure.
Commit: 93ae0834ec6b8a323e92d5f32c8d92e4c6b2967b
