### ISSUE TITLE
Equations not rendered

### ISSUE THREAD

**Issue by jgosmann** [ctn-waterloo/website#55]
Equations on the [synaptic time constants page](http://compneuro.uwaterloo.ca/research/constants-constraints/neurotransmitter-time-constants-pscs.html) are not rendered, making it hard to read.

**Comment by arvoelke** [comment]
I think it's been broken across the whole site for a while now. e.g., http://compneuro.uwaterloo.ca/publications/voelker2015.html

I thought I opened an issue for this already, but apparently not! IIRC @astoeckel noticed this too, but forget if he said he was going to figure out why (maybe not, but worth asking)?

**Comment by arvoelke** [comment]
I just remembered... the main CDN server for MathJax was shut down at the end of April 2017. This might be the reason why. Third-party servers are available if this was indeed the reason.

**Comment by astoeckel** [comment]
MathJax shutting down its CDN is indeet the reason. See https://www.mathjax.org/cdn-shutting-down/

**Comment by astoeckel** [comment]
@jgosmann Created a PR. Please have a look and merge if OK.

> @astoeckel noticed this too, but forget if he said he was going to figure out why (maybe not, but worth asking)?

Yeah, I said I was going to look into this, but ultimately forgot to. Well, now I did ;-)

**Comment by jgosmann** [comment]
Still not fixed ...

**Comment by arvoelke** [comment]
It's working for me. Maybe try force refresh? Does your console give any warnings?

**Comment by jgosmann** [comment]
This is weird. It was *not* working despite a force refresh, but when I checked in the developer tools that the JS file gets requested it suddenly started working. 😖
