### ISSUE TITLE
Host site on Netlify

### ISSUE THREAD

**Issue by Seanny123** [ctn-waterloo/website#57]
Although no one is currently working on this website and it's honestly serving it's purpose pretty well, I thought I would share an experience I had deploying my own static site.

My (tragically ugly) [personal website](https://seanaubin.com/) is create using the static site generator Hugo \[1]. Previously, similar to this website, I would host it on GitHub pages, which made it awkward to deploy. When I de-activated my GitHub Pro account, my GitHub pages went down, so I was forced to move to Netlify.

Using Netlify, I was able to make single step deployment (just commit to the repo!) and reduce the update time for my site to seconds. It also only took me 30 minutes to switch over. For the CTN website, if switched to Netlify, the weird VPN uploady thing wouldn't be necessary anymore and we wouldn't have to use TravisCI to monitor the builds.

# Summary

If someone wants to make the update process of this website less painful, Netlify is a good candidate.

\[1] I chose Hugo because it's fast and I didn't expect to do anything fancy.

**Comment by tbekolay** [comment]
Unfortunately I think the reason this site has to be done this way is because UWaterloo won't point a `uwaterloo.ca` domain to a host off campus.

**Comment by Seanny123** [comment]
I did not realize this.

**Comment by jgosmann** [comment]
Side note: I've also been using Hugo for my [new personal website](https://www.jgosmann.de) and a [new blog I'm in the process of putting together](https://adventures.jgosmann.de). Besides being fast, I like that Hugo doesn't impose any taxonomy/structure (like assuming that there is something like posts) onto your website and you are free to define your own.
