### ISSUE TITLE
PDF file links are broken

### ISSUE THREAD

**Issue by jgosmann** [ctn-waterloo/website#70]
For example:

* On [this page](http://compneuro.uwaterloo.ca/publications/gosmann2015a.html) link to the [PDF](http://compneuro.uwaterloo.ca/files/publications/gosmann.2015a.pdf)
* On [this page](http://compneuro.uwaterloo.ca/publications/stewart2011.html) link to the [PDF](http://compneuro.uwaterloo.ca/files/publications/stewart.2011.pdf)
* probably more/all such links

**Comment by astoeckel** [comment]
Thanks for reporting. Apparently my new deployment script didn't create the symlink to the "files" directory.
